---
version: "3"
services:
  pxe:
    image: lscr.io/linuxserver/netbootxyz:latest
    container_name: olympus.pxe
    environment:
      - PUID=1000
      - PGID=1000
      - MENU_VERSION=2.0.59
      - PORT_RANGE=30000:30010
      - SUBFOLDER=/
    volumes:
      - ./config:/config
      - ./assets:/assets
    ports:
      - 3000:3000
      - 69:69/udp
      - 8080:80
    restart: unless-stopped